/**
 * Mock数据服务 V3.1
 * 更新产品树结构：产品版本 → Feature → Feature版本 → 模块版本
 * 补充项目数据和里程碑数据
 */

import type {
  ProductLine,
  Product,
  ProductVersion,
  Feature,
  Epic,
  FeatureRequirement,
  ModuleRequirement,
  SSTS,
  DomainProject,
  Baseline,
  PI,
  Milestone,
  Sprint,
} from '../types/domain'

/**
 * Feature版本接口（新增）
 */
export interface FeatureVersion {
  id: string
  featureId: string
  version: string
  status: 'PLANNING' | 'IN_PROGRESS' | 'DONE' | 'RELEASED'
  targetDate: string
  moduleVersions?: ModuleVersion[]
}

/**
 * 模块版本接口（更新归属）
 */
export interface ModuleVersion {
  id: string
  featureVersionId: string  // 归属Feature版本
  moduleId: string
  moduleName: string
  version: string
  teamId: string
  teamName: string
  status: 'PLANNING' | 'IN_PROGRESS' | 'DONE'
  features?: Feature[]
}

class MockDataServiceV3_1 {
  /**
   * 生成产品树数据（新结构）
   * 产品线 → 产品 → 产品版本 → Feature → Feature版本 → 模块版本
   */
  generateProductTree(): ProductLine[] {
    return [
      {
        id: 'pl-adas',
        name: '智能驾驶产品线',
        code: 'ADAS',
        description: '涵盖L2-L4级别的智能驾驶产品',
        products: [
          // 产品1：城市NOA
          {
            id: 'p-noa',
            productLineId: 'pl-adas',
            name: '城市NOA',
            code: 'NOA-CITY',
            description: '城市道路导航辅助驾驶',
            owner: '王五（VPM）',
            status: 'IN_PROGRESS',
            versions: [
              // 版本1.0（已发布）
              {
                id: 'pv-noa-1.0',
                productId: 'p-noa',
                version: 'V1.0',
                releaseDate: '2025-12-01',
                status: 'RELEASED',
                baselineId: 'bl-sop-2025',
                features: [
                  // Feature1: LKA车道保持
                  {
                    id: 'feat-lka',
                    productId: 'p-noa',
                    name: 'LKA车道保持',
                    code: 'FEAT-LKA',
                    description: '车道保持辅助功能',
                    status: 'DONE',
                    maturity: 100,
                    completion: 100,
                    isFrozen: true,
                    processStage: 'S9',
                    owner: '张三（PO）',
                    featureVersions: [
                      {
                        id: 'fv-lka-1.0',
                        featureId: 'feat-lka',
                        version: 'V1.0',
                        status: 'RELEASED',
                        targetDate: '2025-12-01',
                        moduleVersions: [
                          {
                            id: 'mv-lka-perception-1.0',
                            featureVersionId: 'fv-lka-1.0',
                            moduleId: 'm-perception',
                            moduleName: '感知模块',
                            version: 'V1.0',
                            teamId: 'team-perception',
                            teamName: '感知团队',
                            status: 'DONE',
                          },
                          {
                            id: 'mv-lka-control-1.0',
                            featureVersionId: 'fv-lka-1.0',
                            moduleId: 'm-control',
                            moduleName: '控制模块',
                            version: 'V1.0',
                            teamId: 'team-control',
                            teamName: '控制团队',
                            status: 'DONE',
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
              // 版本1.1（进行中）
              {
                id: 'pv-noa-1.1',
                productId: 'p-noa',
                version: 'V1.1',
                releaseDate: '2026-06-30',
                status: 'IN_PROGRESS',
                baselineId: 'bl-sop-2026',
                features: [
                  // Feature1: LKA车道保持（新版本）
                  {
                    id: 'feat-lka-v1.1',
                    productId: 'p-noa',
                    name: 'LKA车道保持',
                    code: 'FEAT-LKA',
                    description: '增强版车道保持',
                    status: 'IN_PROGRESS',
                    maturity: 85,
                    completion: 60,
                    isFrozen: false,
                    processStage: 'S6',
                    owner: '张三（PO）',
                    featureVersions: [
                      {
                        id: 'fv-lka-1.1',
                        featureId: 'feat-lka-v1.1',
                        version: 'V1.1',
                        status: 'IN_PROGRESS',
                        targetDate: '2026-06-30',
                        moduleVersions: [
                          {
                            id: 'mv-lka-perception-1.1',
                            featureVersionId: 'fv-lka-1.1',
                            moduleId: 'm-perception',
                            moduleName: '感知模块',
                            version: 'V1.1',
                            teamId: 'team-perception',
                            teamName: '感知团队',
                            status: 'IN_PROGRESS',
                          },
                          {
                            id: 'mv-lka-control-1.1',
                            featureVersionId: 'fv-lka-1.1',
                            moduleId: 'm-control',
                            moduleName: '控制模块',
                            version: 'V1.1',
                            teamId: 'team-control',
                            teamName: '控制团队',
                            status: 'IN_PROGRESS',
                          },
                        ],
                      },
                    ],
                  },
                  // Feature2: ACC自适应巡航
                  {
                    id: 'feat-acc',
                    productId: 'p-noa',
                    name: 'ACC自适应巡航',
                    code: 'FEAT-ACC',
                    description: '自适应巡航控制',
                    status: 'IN_PROGRESS',
                    maturity: 92,
                    completion: 75,
                    isFrozen: false,
                    processStage: 'S7',
                    owner: '李四（PO）',
                    featureVersions: [
                      {
                        id: 'fv-acc-1.1',
                        featureId: 'feat-acc',
                        version: 'V1.1',
                        status: 'IN_PROGRESS',
                        targetDate: '2026-06-30',
                        moduleVersions: [
                          {
                            id: 'mv-acc-perception-1.1',
                            featureVersionId: 'fv-acc-1.1',
                            moduleId: 'm-perception',
                            moduleName: '感知模块',
                            version: 'V1.1',
                            teamId: 'team-perception',
                            teamName: '感知团队',
                            status: 'IN_PROGRESS',
                          },
                          {
                            id: 'mv-acc-planning-1.1',
                            featureVersionId: 'fv-acc-1.1',
                            moduleId: 'm-planning',
                            moduleName: '规划模块',
                            version: 'V1.1',
                            teamId: 'team-planning',
                            teamName: '规划团队',
                            status: 'IN_PROGRESS',
                          },
                        ],
                      },
                    ],
                  },
                  // Feature3: AEB自动紧急制动
                  {
                    id: 'feat-aeb',
                    productId: 'p-noa',
                    name: 'AEB自动紧急制动',
                    code: 'FEAT-AEB',
                    description: '自动紧急制动系统',
                    status: 'IN_PROGRESS',
                    maturity: 88,
                    completion: 50,
                    isFrozen: false,
                    processStage: 'S6',
                    owner: '王五（PO）',
                    featureVersions: [
                      {
                        id: 'fv-aeb-1.1',
                        featureId: 'feat-aeb',
                        version: 'V1.1',
                        status: 'IN_PROGRESS',
                        targetDate: '2026-06-30',
                        moduleVersions: [
                          {
                            id: 'mv-aeb-perception-1.1',
                            featureVersionId: 'fv-aeb-1.1',
                            moduleId: 'm-perception',
                            moduleName: '感知模块',
                            version: 'V1.1',
                            teamId: 'team-perception',
                            teamName: '感知团队',
                            status: 'IN_PROGRESS',
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },
          // 产品2：自动泊车
          {
            id: 'p-apa',
            productLineId: 'pl-adas',
            name: '自动泊车',
            code: 'APA',
            description: '自动泊车辅助系统',
            owner: '赵六（VPM）',
            status: 'IN_PROGRESS',
            versions: [
              {
                id: 'pv-apa-1.0',
                productId: 'p-apa',
                version: 'V1.0',
                releaseDate: '2026-03-31',
                status: 'IN_PROGRESS',
                baselineId: 'bl-apa-2026',
                features: [
                  {
                    id: 'feat-apa-park',
                    productId: 'p-apa',
                    name: 'APA自动泊车',
                    code: 'FEAT-APA-PARK',
                    description: '垂直泊车功能',
                    status: 'IN_PROGRESS',
                    maturity: 90,
                    completion: 80,
                    isFrozen: false,
                    processStage: 'S7',
                    owner: '孙七（PO）',
                    featureVersions: [
                      {
                        id: 'fv-apa-1.0',
                        featureId: 'feat-apa-park',
                        version: 'V1.0',
                        status: 'IN_PROGRESS',
                        targetDate: '2026-03-31',
                        moduleVersions: [
                          {
                            id: 'mv-apa-perception-1.0',
                            featureVersionId: 'fv-apa-1.0',
                            moduleId: 'm-perception',
                            moduleName: '感知模块（APA）',
                            version: 'V1.0',
                            teamId: 'team-perception',
                            teamName: '感知团队',
                            status: 'IN_PROGRESS',
                          },
                          {
                            id: 'mv-apa-planning-1.0',
                            featureVersionId: 'fv-apa-1.0',
                            moduleId: 'm-planning',
                            moduleName: '规划模块（APA）',
                            version: 'V1.0',
                            teamId: 'team-planning',
                            teamName: '规划团队',
                            status: 'IN_PROGRESS',
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },
          // 产品3：高速NOA
          {
            id: 'p-hnoa',
            productLineId: 'pl-adas',
            name: '高速NOA',
            code: 'NOA-HIGHWAY',
            description: '高速公路导航辅助驾驶',
            owner: '周八（VPM）',
            status: 'IN_PROGRESS',
            versions: [
              {
                id: 'pv-hnoa-2.0',
                productId: 'p-hnoa',
                version: 'V2.0',
                releaseDate: '2026-09-30',
                status: 'IN_PROGRESS',
                baselineId: 'bl-hnoa-2026',
                features: [
                  {
                    id: 'feat-hnoa-cruise',
                    productId: 'p-hnoa',
                    name: '高速巡航',
                    code: 'FEAT-HNOA-CRUISE',
                    description: '高速公路自动巡航',
                    status: 'IN_PROGRESS',
                    maturity: 88,
                    completion: 70,
                    isFrozen: false,
                    processStage: 'S6',
                    owner: '吴九（PO）',
                    featureVersions: [
                      {
                        id: 'fv-hnoa-cruise-2.0',
                        featureId: 'feat-hnoa-cruise',
                        version: 'V2.0',
                        status: 'IN_PROGRESS',
                        targetDate: '2026-09-30',
                        moduleVersions: [
                          {
                            id: 'mv-hnoa-perception-2.0',
                            featureVersionId: 'fv-hnoa-cruise-2.0',
                            moduleId: 'm-perception',
                            moduleName: '感知模块',
                            version: 'V2.0',
                            teamId: 'team-perception',
                            teamName: '感知团队',
                            status: 'IN_PROGRESS',
                          },
                          {
                            id: 'mv-hnoa-planning-2.0',
                            featureVersionId: 'fv-hnoa-cruise-2.0',
                            moduleId: 'm-planning',
                            moduleName: '规划模块',
                            version: 'V2.0',
                            teamId: 'team-planning',
                            teamName: '规划团队',
                            status: 'IN_PROGRESS',
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ]
  }

  /**
   * 生成12个造车节点数据（新架构）⭐
   */
  generateVehicleNodeProjectTree(): DomainProject[] {
    return [
      {
        id: 'proj-dreamcar-adas',
        name: '岚图梦想家 ADAS项目',
        code: 'DREAMCAR-ADAS',
        description: '岚图梦想家车型的智能驾驶系统项目（L2+级别）',
        domain: 'ADAS',
        vehicleModel: '岚图梦想家',
        projectType: 'NEW',
        startDate: '2025-08-01',
        endDate: '2026-06-30',
        status: 'IN_PROGRESS',
        vehicleNodes: [
          // 1. PSI - 项目战略目的
          {
            id: 'vn-psi',
            projectId: 'proj-dreamcar-adas',
            code: 'PSI',
            name: 'PSI',
            fullName: 'PSI - 项目战略目的',
            description: '项目战略目标定义，市场定位分析，技术路线规划',
            phase: 'PLANNING',
            sequence: 1,
            startDate: '2025-08-01',
            targetDate: '2025-08-31',
            status: 'DONE',
            gateways: [],
            productVersions: [],
            sprints: [],
            maturity: 100,
            completion: 100,
          },
          // 2. PTR - 项目技术要求
          {
            id: 'vn-ptr',
            projectId: 'proj-dreamcar-adas',
            code: 'PTR',
            name: 'PTR',
            fullName: 'PTR - 项目技术要求',
            description: '技术规格书制定，技术可行性分析，技术方案选型',
            phase: 'PLANNING',
            sequence: 2,
            startDate: '2025-09-01',
            targetDate: '2025-09-30',
            status: 'DONE',
            gateways: [],
            productVersions: [],
            sprints: [],
            maturity: 100,
            completion: 100,
          },
          // 3. PSF - 项目战略最终化
          {
            id: 'vn-psf',
            projectId: 'proj-dreamcar-adas',
            code: 'PSF',
            name: 'PSF',
            fullName: 'PSF - 项目战略最终化',
            description: '战略方案最终确认，资源预算确认，项目范围确认',
            phase: 'PLANNING',
            sequence: 3,
            startDate: '2025-10-01',
            targetDate: '2025-10-15',
            status: 'DONE',
            gateways: [],
            productVersions: [],
            sprints: [],
            maturity: 100,
            completion: 100,
          },
          // 4. PS - 项目开始/立项完成
          {
            id: 'vn-ps',
            projectId: 'proj-dreamcar-adas',
            code: 'PS',
            name: 'PS',
            fullName: 'PS - 项目开始/立项完成',
            description: '项目正式启动，团队组建，项目章程发布',
            phase: 'INITIATION',
            sequence: 4,
            startDate: '2025-10-16',
            targetDate: '2025-10-31',
            status: 'DONE',
            gateways: [
              {
                id: 'gw-fc3',
                vehicleNodeId: 'vn-ps',
                code: 'FC3',
                name: 'FC3 - 功能需求锁定点',
                date: '2025-10-31',
                criteria: '功能需求规格书完成，需求评审通过',
                status: 'PASSED',
                importance: 'HIGH',
              },
            ],
            productVersions: [
              {
                id: 'pv-ps-noa',
                baselineId: 'vn-ps',
                productVersionId: 'pv-noa-0.1',
                productName: '城市NOA',
                version: 'V0.1',
                targetDate: '2025-10-31',
                status: 'DONE',
                completion: 100,
                estimatedHours: 3000,
                sprints: ['sprint-ps-1', 'sprint-ps-2'],
              },
              {
                id: 'pv-ps-cabin',
                baselineId: 'vn-ps',
                productVersionId: 'pv-cabin-0.1',
                productName: '智能座舱',
                version: 'V0.1',
                targetDate: '2025-10-31',
                status: 'DONE',
                completion: 100,
                estimatedHours: 2000,
                sprints: ['sprint-ps-3'],
              },
            ],
            sprints: [
              {
                id: 'sprint-ps-1',
                name: 'PS Sprint 1',
                code: 'SP-PS-1',
                teamId: 't-noa',
                teamName: 'NOA团队',
                startDate: '2025-10-16',
                endDate: '2025-10-23',
                capacity: 40,
                committed: 38,
                completed: 38,
                status: 'DONE',
              },
              {
                id: 'sprint-ps-2',
                name: 'PS Sprint 2',
                code: 'SP-PS-2',
                teamId: 't-noa',
                teamName: 'NOA团队',
                startDate: '2025-10-24',
                endDate: '2025-10-31',
                capacity: 40,
                committed: 40,
                completed: 40,
                status: 'DONE',
              },
              {
                id: 'sprint-ps-3',
                name: 'PS Sprint 1 (座舱)',
                code: 'SP-PS-CABIN-1',
                teamId: 't-cabin',
                teamName: '座舱团队',
                startDate: '2025-10-16',
                endDate: '2025-10-31',
                capacity: 50,
                committed: 48,
                completed: 48,
                status: 'DONE',
              },
            ],
            maturity: 100,
            completion: 100,
          },
          // 5. PC - 项目确认
          {
            id: 'vn-pc',
            projectId: 'proj-dreamcar-adas',
            code: 'PC',
            name: 'PC',
            fullName: 'PC - 项目确认',
            description: '项目方案评审，技术路线确认，资源配置确认',
            phase: 'INITIATION',
            sequence: 5,
            startDate: '2025-11-01',
            targetDate: '2025-11-15',
            status: 'DONE',
            gateways: [],
            productVersions: [],
            sprints: [],
            maturity: 100,
            completion: 100,
          },
          // 6. PA - 项目批准
          {
            id: 'vn-pa',
            projectId: 'proj-dreamcar-adas',
            code: 'PA',
            name: 'PA',
            fullName: 'PA - 项目批准',
            description: '项目正式批准，详细设计启动，开发环境准备',
            phase: 'INITIATION',
            sequence: 6,
            startDate: '2025-11-16',
            targetDate: '2025-12-15',
            status: 'DONE',
            gateways: [
              {
                id: 'gw-fdj',
                vehicleNodeId: 'vn-pa',
                code: 'FDJ',
                name: 'FDJ - 单元开发完成/最终数据判定',
                date: '2025-12-15',
                criteria: '详细设计完成，开发环境就绪',
                status: 'PASSED',
                importance: 'MEDIUM',
              },
            ],
            productVersions: [
              {
                id: 'pv-pa-noa',
                baselineId: 'vn-pa',
                productVersionId: 'pv-noa-0.5',
                productName: '城市NOA',
                version: 'V0.5',
                targetDate: '2025-12-15',
                status: 'DONE',
                completion: 100,
                estimatedHours: 5000,
                sprints: ['sprint-pa-1', 'sprint-pa-2'],
              },
              {
                id: 'pv-pa-cabin',
                baselineId: 'vn-pa',
                productVersionId: 'pv-cabin-0.5',
                productName: '智能座舱',
                version: 'V0.5',
                targetDate: '2025-12-15',
                status: 'DONE',
                completion: 100,
                estimatedHours: 4000,
                sprints: ['sprint-pa-3', 'sprint-pa-4'],
              },
            ],
            sprints: [
              {
                id: 'sprint-pa-1',
                name: 'PA Sprint 1',
                code: 'SP-PA-1',
                teamId: 't-noa',
                teamName: 'NOA团队',
                startDate: '2025-11-16',
                endDate: '2025-11-30',
                capacity: 80,
                committed: 78,
                completed: 78,
                status: 'DONE',
              },
              {
                id: 'sprint-pa-2',
                name: 'PA Sprint 2',
                code: 'SP-PA-2',
                teamId: 't-noa',
                teamName: 'NOA团队',
                startDate: '2025-12-01',
                endDate: '2025-12-15',
                capacity: 80,
                committed: 80,
                completed: 80,
                status: 'DONE',
              },
              {
                id: 'sprint-pa-3',
                name: 'PA Sprint 1 (座舱)',
                code: 'SP-PA-CABIN-1',
                teamId: 't-cabin',
                teamName: '座舱团队',
                startDate: '2025-11-16',
                endDate: '2025-11-30',
                capacity: 70,
                committed: 68,
                completed: 68,
                status: 'DONE',
              },
              {
                id: 'sprint-pa-4',
                name: 'PA Sprint 2 (座舱)',
                code: 'SP-PA-CABIN-2',
                teamId: 't-cabin',
                teamName: '座舱团队',
                startDate: '2025-12-01',
                endDate: '2025-12-15',
                capacity: 70,
                committed: 70,
                completed: 70,
                status: 'DONE',
              },
            ],
            maturity: 100,
            completion: 100,
          },
          // 7. VP - 验证样车/样车确认 ⭐⭐⭐ (最复杂最重要)
          {
            id: 'vn-vp',
            projectId: 'proj-dreamcar-adas',
            code: 'VP',
            name: 'VP',
            fullName: 'VP - 验证样车/样车确认',
            description: '样车验证阶段，包含VP1/VP2/VP3三个子阶段，周期长，Gateway最多',
            phase: 'DEVELOPMENT',
            sequence: 7,
            startDate: '2025-12-16',
            targetDate: '2026-03-31',
            status: 'IN_PROGRESS',
            gateways: [
              // VP共用Gateway
              {
                id: 'gw-swrs',
                vehicleNodeId: 'vn-vp',
                code: 'SWRS',
                name: 'SWRS释放 - 软件需求规格书释放',
                date: '2026-01-15',
                criteria: 'SWRS文档完成并评审通过',
                status: 'PASSED',
                importance: 'HIGH',
              },
              {
                id: 'gw-sdb',
                vehicleNodeId: 'vn-vp',
                code: 'SDB',
                name: 'SDB释放 - 系统设计基线释放',
                date: '2026-02-01',
                criteria: 'SDB文档完成并评审通过',
                status: 'PASSED',
                importance: 'HIGH',
              },
              {
                id: 'gw-req-freeze',
                vehicleNodeId: 'vn-vp',
                code: 'REQ_FREEZE',
                name: '功能需求变更锁定',
                date: '2026-02-28',
                criteria: '需求冻结，不再接受新需求',
                status: 'PENDING',
                importance: 'HIGH',
              },
              {
                id: 'gw-mrd-crb',
                vehicleNodeId: 'vn-vp',
                code: 'MRD_CRB',
                name: 'MRD-CRB - 模块需求文档变更评审委员会',
                date: '2026-03-15',
                criteria: '所有MRD评审完成',
                status: 'PENDING',
                importance: 'MEDIUM',
              },
            ],
            subPhases: [
              {
                id: 'vp1',
                vehicleNodeId: 'vn-vp',
                code: 'VP1',
                name: 'VP1 - 初步样车验证',
                targetDate: '2026-01-15',
                status: 'DONE',
                gateways: [
                  {
                    id: 'gw-vp1',
                    vpSubPhaseId: 'vp1',
                    code: 'VP1_GATE',
                    name: 'VP1门禁 - 初步样车验证',
                    date: '2026-01-15',
                    criteria: '初步样车验证通过，功能完成度≥60%',
                    status: 'PASSED',
                    importance: 'HIGH',
                  },
                ],
              },
              {
                id: 'vp2',
                vehicleNodeId: 'vn-vp',
                code: 'VP2',
                name: 'VP2 - 中期样车验证',
                targetDate: '2026-02-28',
                status: 'IN_PROGRESS',
                gateways: [
                  {
                    id: 'gw-vp2',
                    vpSubPhaseId: 'vp2',
                    code: 'VP2_GATE',
                    name: 'VP2门禁 - 中期样车验证',
                    date: '2026-02-28',
                    criteria: '中期样车验证通过，功能完成度≥80%',
                    status: 'PENDING',
                    importance: 'HIGH',
                  },
                ],
              },
              {
                id: 'vp3',
                vehicleNodeId: 'vn-vp',
                code: 'VP3',
                name: 'VP3 - 最终样车验证',
                targetDate: '2026-03-31',
                status: 'PLANNING',
                gateways: [
                  {
                    id: 'gw-vp3',
                    vpSubPhaseId: 'vp3',
                    code: 'VP3_GATE',
                    name: 'VP3门禁 - 最终样车验证',
                    date: '2026-03-31',
                    criteria: '最终样车验证通过，功能完成度≥95%',
                    status: 'PENDING',
                    importance: 'HIGH',
                  },
                ],
              },
            ],
            productVersions: [
              {
                id: 'pv-vp-noa',
                baselineId: 'vn-vp',
                productVersionId: 'pv-noa-1.0',
                productName: '城市NOA',
                version: 'V1.0',
                targetDate: '2026-03-31',
                status: 'IN_PROGRESS',
                completion: 70,
                estimatedHours: 20000,
                sprints: ['sprint-vp-1', 'sprint-vp-2', 'sprint-vp-3', 'sprint-vp-4', 'sprint-vp-5', 'sprint-vp-6'],
              },
              {
                id: 'pv-vp-cabin',
                baselineId: 'vn-vp',
                productVersionId: 'pv-cabin-1.0',
                productName: '智能座舱',
                version: 'V1.0',
                targetDate: '2026-03-31',
                status: 'IN_PROGRESS',
                completion: 75,
                estimatedHours: 18000,
                sprints: ['sprint-vp-7', 'sprint-vp-8', 'sprint-vp-9', 'sprint-vp-10'],
              },
              {
                id: 'pv-vp-ee',
                baselineId: 'vn-vp',
                productVersionId: 'pv-ee-1.0',
                productName: '电子电器架构',
                version: 'E4',
                targetDate: '2026-03-31',
                status: 'IN_PROGRESS',
                completion: 65,
                estimatedHours: 15000,
                sprints: ['sprint-vp-11', 'sprint-vp-12'],
              },
            ],
            sprints: [
              // NOA团队 Sprints (6个)
              {
                id: 'sprint-vp-1',
                name: 'VP Sprint 1 (NOA)',
                code: 'SP-VP-NOA-1',
                teamId: 't-noa',
                teamName: 'NOA团队',
                startDate: '2025-12-16',
                endDate: '2025-12-31',
                capacity: 100,
                committed: 95,
                completed: 95,
                status: 'DONE',
              },
              {
                id: 'sprint-vp-2',
                name: 'VP Sprint 2 (NOA)',
                code: 'SP-VP-NOA-2',
                teamId: 't-noa',
                teamName: 'NOA团队',
                startDate: '2026-01-01',
                endDate: '2026-01-15',
                capacity: 100,
                committed: 98,
                completed: 98,
                status: 'DONE',
              },
              {
                id: 'sprint-vp-3',
                name: 'VP Sprint 3 (NOA)',
                code: 'SP-VP-NOA-3',
                teamId: 't-noa',
                teamName: 'NOA团队',
                startDate: '2026-01-16',
                endDate: '2026-01-31',
                capacity: 100,
                committed: 100,
                completed: 100,
                status: 'DONE',
              },
              {
                id: 'sprint-vp-4',
                name: 'VP Sprint 4 (NOA)',
                code: 'SP-VP-NOA-4',
                teamId: 't-noa',
                teamName: 'NOA团队',
                startDate: '2026-02-01',
                endDate: '2026-02-28',
                capacity: 120,
                committed: 118,
                completed: 90,
                status: 'IN_PROGRESS',
              },
              {
                id: 'sprint-vp-5',
                name: 'VP Sprint 5 (NOA)',
                code: 'SP-VP-NOA-5',
                teamId: 't-noa',
                teamName: 'NOA团队',
                startDate: '2026-03-01',
                endDate: '2026-03-15',
                capacity: 100,
                committed: 100,
                completed: 0,
                status: 'PLANNING',
              },
              {
                id: 'sprint-vp-6',
                name: 'VP Sprint 6 (NOA)',
                code: 'SP-VP-NOA-6',
                teamId: 't-noa',
                teamName: 'NOA团队',
                startDate: '2026-03-16',
                endDate: '2026-03-31',
                capacity: 100,
                committed: 100,
                completed: 0,
                status: 'PLANNING',
              },
              // 座舱团队 Sprints (4个)
              {
                id: 'sprint-vp-7',
                name: 'VP Sprint 1 (座舱)',
                code: 'SP-VP-CABIN-1',
                teamId: 't-cabin',
                teamName: '座舱团队',
                startDate: '2025-12-16',
                endDate: '2026-01-15',
                capacity: 150,
                committed: 145,
                completed: 145,
                status: 'DONE',
              },
              {
                id: 'sprint-vp-8',
                name: 'VP Sprint 2 (座舱)',
                code: 'SP-VP-CABIN-2',
                teamId: 't-cabin',
                teamName: '座舱团队',
                startDate: '2026-01-16',
                endDate: '2026-02-15',
                capacity: 150,
                committed: 150,
                completed: 150,
                status: 'DONE',
              },
              {
                id: 'sprint-vp-9',
                name: 'VP Sprint 3 (座舱)',
                code: 'SP-VP-CABIN-3',
                teamId: 't-cabin',
                teamName: '座舱团队',
                startDate: '2026-02-16',
                endDate: '2026-03-15',
                capacity: 150,
                committed: 148,
                completed: 100,
                status: 'IN_PROGRESS',
              },
              {
                id: 'sprint-vp-10',
                name: 'VP Sprint 4 (座舱)',
                code: 'SP-VP-CABIN-4',
                teamId: 't-cabin',
                teamName: '座舱团队',
                startDate: '2026-03-16',
                endDate: '2026-03-31',
                capacity: 150,
                committed: 150,
                completed: 0,
                status: 'PLANNING',
              },
              // 电子电器团队 Sprints (2个)
              {
                id: 'sprint-vp-11',
                name: 'VP Sprint 1 (EE)',
                code: 'SP-VP-EE-1',
                teamId: 't-ee',
                teamName: 'EE架构团队',
                startDate: '2025-12-16',
                endDate: '2026-02-15',
                capacity: 200,
                committed: 195,
                completed: 195,
                status: 'DONE',
              },
              {
                id: 'sprint-vp-12',
                name: 'VP Sprint 2 (EE)',
                code: 'SP-VP-EE-2',
                teamId: 't-ee',
                teamName: 'EE架构团队',
                startDate: '2026-02-16',
                endDate: '2026-03-31',
                capacity: 200,
                committed: 200,
                completed: 80,
                status: 'IN_PROGRESS',
              },
            ],
            maturity: 85,
            completion: 70,
          },
          // 8. LR - 投产准备
          {
            id: 'vn-lr',
            projectId: 'proj-dreamcar-adas',
            code: 'LR',
            name: 'LR',
            fullName: 'LR - 投产准备',
            description: '生产线准备，工装测试，供应链准备',
            phase: 'PRODUCTION',
            sequence: 8,
            startDate: '2026-04-01',
            targetDate: '2026-04-30',
            status: 'PLANNING',
            gateways: [
              {
                id: 'gw-1pp',
                vehicleNodeId: 'vn-lr',
                code: '1PP',
                name: '1PP - 投产就绪 (First Pre-Production)',
                date: '2026-04-15',
                criteria: '生产线就绪，工装测试通过',
                status: 'PENDING',
                importance: 'HIGH',
              },
              {
                id: 'gw-tt',
                vehicleNodeId: 'vn-lr',
                code: 'TT',
                name: 'TT - 工装测试 (Tooling Trial)',
                date: '2026-04-30',
                criteria: '工装测试完成，质量验证通过',
                status: 'PENDING',
                importance: 'MEDIUM',
              },
            ],
            productVersions: [
              {
                id: 'pv-lr-noa',
                baselineId: 'vn-lr',
                productVersionId: 'pv-noa-1.5',
                productName: '城市NOA',
                version: 'V1.5',
                targetDate: '2026-04-30',
                status: 'PLANNING',
                completion: 0,
                estimatedHours: 8000,
                sprints: ['sprint-lr-1', 'sprint-lr-2'],
              },
              {
                id: 'pv-lr-cabin',
                baselineId: 'vn-lr',
                productVersionId: 'pv-cabin-1.5',
                productName: '智能座舱',
                version: 'V1.5',
                targetDate: '2026-04-30',
                status: 'PLANNING',
                completion: 0,
                estimatedHours: 6000,
                sprints: ['sprint-lr-3'],
              },
            ],
            sprints: [
              {
                id: 'sprint-lr-1',
                name: 'LR Sprint 1',
                code: 'SP-LR-1',
                teamId: 't-noa',
                teamName: 'NOA团队',
                startDate: '2026-04-01',
                endDate: '2026-04-15',
                capacity: 80,
                committed: 0,
                completed: 0,
                status: 'PLANNING',
              },
              {
                id: 'sprint-lr-2',
                name: 'LR Sprint 2',
                code: 'SP-LR-2',
                teamId: 't-noa',
                teamName: 'NOA团队',
                startDate: '2026-04-16',
                endDate: '2026-04-30',
                capacity: 80,
                committed: 0,
                completed: 0,
                status: 'PLANNING',
              },
              {
                id: 'sprint-lr-3',
                name: 'LR Sprint 1 (座舱)',
                code: 'SP-LR-CABIN-1',
                teamId: 't-cabin',
                teamName: '座舱团队',
                startDate: '2026-04-01',
                endDate: '2026-04-30',
                capacity: 120,
                committed: 0,
                completed: 0,
                status: 'PLANNING',
              },
            ],
            maturity: 50,
            completion: 0,
          },
          // 9. LS - 投产验收
          {
            id: 'vn-ls',
            projectId: 'proj-dreamcar-adas',
            code: 'LS',
            name: 'LS',
            fullName: 'LS - 投产验收',
            description: '投产验收检查，试生产执行，质量确认',
            phase: 'PRODUCTION',
            sequence: 9,
            startDate: '2026-05-01',
            targetDate: '2026-05-31',
            status: 'PLANNING',
            gateways: [
              {
                id: 'gw-2pp',
                vehicleNodeId: 'vn-ls',
                code: '2PP',
                name: '2PP/SOP - 投产签收 (Second Pre-Production)',
                date: '2026-05-20',
                criteria: '试生产完成，质量达标',
                status: 'PENDING',
                importance: 'HIGH',
              },
              {
                id: 'gw-pp',
                vehicleNodeId: 'vn-ls',
                code: 'PP',
                name: 'PP - 试生产 (Pilot Production)',
                date: '2026-05-31',
                criteria: '试生产验证通过',
                status: 'PENDING',
                importance: 'MEDIUM',
              },
            ],
            productVersions: [
              {
                id: 'pv-ls-noa',
                baselineId: 'vn-ls',
                productVersionId: 'pv-noa-2.0',
                productName: '城市NOA',
                version: 'V2.0',
                targetDate: '2026-05-31',
                status: 'PLANNING',
                completion: 0,
                estimatedHours: 5000,
                sprints: ['sprint-ls-1', 'sprint-ls-2'],
              },
              {
                id: 'pv-ls-cabin',
                baselineId: 'vn-ls',
                productVersionId: 'pv-cabin-2.0',
                productName: '智能座舱',
                version: 'V2.0',
                targetDate: '2026-05-31',
                status: 'PLANNING',
                completion: 0,
                estimatedHours: 4000,
                sprints: ['sprint-ls-3'],
              },
            ],
            sprints: [
              {
                id: 'sprint-ls-1',
                name: 'LS Sprint 1',
                code: 'SP-LS-1',
                teamId: 't-noa',
                teamName: 'NOA团队',
                startDate: '2026-05-01',
                endDate: '2026-05-15',
                capacity: 60,
                committed: 0,
                completed: 0,
                status: 'PLANNING',
              },
              {
                id: 'sprint-ls-2',
                name: 'LS Sprint 2',
                code: 'SP-LS-2',
                teamId: 't-noa',
                teamName: 'NOA团队',
                startDate: '2026-05-16',
                endDate: '2026-05-31',
                capacity: 60,
                committed: 0,
                completed: 0,
                status: 'PLANNING',
              },
              {
                id: 'sprint-ls-3',
                name: 'LS Sprint 1 (座舱)',
                code: 'SP-LS-CABIN-1',
                teamId: 't-cabin',
                teamName: '座舱团队',
                startDate: '2026-05-01',
                endDate: '2026-05-31',
                capacity: 100,
                committed: 0,
                completed: 0,
                status: 'PLANNING',
              },
            ],
            maturity: 40,
            completion: 0,
          },
          // 10. J1 - 量产准备 ⭐⭐⭐
          {
            id: 'vn-j1',
            projectId: 'proj-dreamcar-adas',
            code: 'J1',
            name: 'J1',
            fullName: 'J1 - 量产准备',
            description: '正式量产启动，批量生产开始，质量持续监控',
            phase: 'PRODUCTION',
            sequence: 10,
            startDate: '2026-06-01',
            targetDate: '2026-06-30',
            status: 'PLANNING',
            gateways: [
              {
                id: 'gw-sop',
                vehicleNodeId: 'vn-j1',
                code: 'SOP',
                name: 'SOP - 批量生产启动 (Start Of Production)',
                date: '2026-06-30',
                criteria: '所有质量门禁通过，量产条件满足，正式交付客户',
                status: 'PENDING',
                importance: 'HIGH',
              },
            ],
            productVersions: [
              {
                id: 'pv-j1-noa',
                baselineId: 'vn-j1',
                productVersionId: 'pv-noa-2.5',
                productName: '城市NOA',
                version: 'V2.5 (量产版本)',
                targetDate: '2026-06-30',
                status: 'PLANNING',
                completion: 0,
                estimatedHours: 3000,
                sprints: ['sprint-j1-1', 'sprint-j1-2'],
              },
              {
                id: 'pv-j1-cabin',
                baselineId: 'vn-j1',
                productVersionId: 'pv-cabin-2.5',
                productName: '智能座舱',
                version: 'V2.5 (量产版本)',
                targetDate: '2026-06-30',
                status: 'PLANNING',
                completion: 0,
                estimatedHours: 2500,
                sprints: ['sprint-j1-3'],
              },
            ],
            sprints: [
              {
                id: 'sprint-j1-1',
                name: 'J1 Sprint 1',
                code: 'SP-J1-1',
                teamId: 't-noa',
                teamName: 'NOA团队',
                startDate: '2026-06-01',
                endDate: '2026-06-15',
                capacity: 50,
                committed: 0,
                completed: 0,
                status: 'PLANNING',
              },
              {
                id: 'sprint-j1-2',
                name: 'J1 Sprint 2',
                code: 'SP-J1-2',
                teamId: 't-noa',
                teamName: 'NOA团队',
                startDate: '2026-06-16',
                endDate: '2026-06-30',
                capacity: 50,
                committed: 0,
                completed: 0,
                status: 'PLANNING',
              },
              {
                id: 'sprint-j1-3',
                name: 'J1 Sprint 1 (座舱)',
                code: 'SP-J1-CABIN-1',
                teamId: 't-cabin',
                teamName: '座舱团队',
                startDate: '2026-06-01',
                endDate: '2026-06-30',
                capacity: 80,
                committed: 0,
                completed: 0,
                status: 'PLANNING',
              },
            ],
            maturity: 30,
            completion: 0,
          },
          // 11. OKTB - 销售批准
          {
            id: 'vn-oktb',
            projectId: 'proj-dreamcar-adas',
            code: 'OKTB',
            name: 'OKTB',
            fullName: 'OKTB - 销售批准',
            description: '产品最终验证，销售授权，市场准备',
            phase: 'LAUNCH',
            sequence: 11,
            startDate: '2026-07-01',
            targetDate: '2026-07-31',
            status: 'PLANNING',
            gateways: [],
            productVersions: [],
            sprints: [],
            maturity: 20,
            completion: 0,
          },
          // 12. FSR - 最终状态报告/项目关闭
          {
            id: 'vn-fsr',
            projectId: 'proj-dreamcar-adas',
            code: 'FSR',
            name: 'FSR',
            fullName: 'FSR - 项目关闭',
            description: '项目总结，经验教训，项目归档',
            phase: 'CLOSED',
            sequence: 12,
            startDate: '2026-08-01',
            targetDate: '2026-08-31',
            status: 'PLANNING',
            gateways: [],
            productVersions: [],
            sprints: [],
            maturity: 0,
            completion: 0,
          },
        ],
      },
    ]
  }

  /**
   * 生成项目计划树数据（旧架构，保留兼容性）
   */
  generateProjectPlanTree(): DomainProject[] {
    // 完整的里程碑列表（ASPICE标准）
    const standardMilestones = [
      { id: 'ms-vff', code: 'VFF', name: 'VFF-整车功能冻结', targetDate: '2025-12-15', description: '整车功能规格冻结' },
      { id: 'ms-vif', code: 'VIF', name: 'VIF-车辆集成冻结', targetDate: '2026-01-31', description: '车辆集成冻结' },
      { id: 'ms-pvs', code: 'PVS', name: 'PVS-量产验证开始', targetDate: '2026-03-01', description: '量产验证开始' },
      { id: 'ms-sop', code: 'SOP', name: 'SOP-量产启动', targetDate: '2026-06-30', description: '正式量产' },
    ]

    // Gateway节点（质量门禁）
    const standardGateways = [
      { id: 'gw-g1', name: 'G1-项目启动', date: '2025-10-01', criteria: '项目批准、资源到位' },
      { id: 'gw-g2', name: 'G2-需求评审', date: '2025-11-15', criteria: '需求成熟度≥90%' },
      { id: 'gw-g3', name: 'G3-设计评审', date: '2025-12-30', criteria: '架构和接口设计完成' },
      { id: 'gw-g4', name: 'G4-集成测试', date: '2026-04-30', criteria: '系统集成测试通过' },
      { id: 'gw-g5', name: 'G5-SOP就绪', date: '2026-06-15', criteria: '量产条件满足' },
    ]

    return [
      // 项目1：岚图梦想家 ADAS项目
      {
        id: 'proj-dreamcar-adas',
        name: '岚图梦想家 ADAS项目',
        code: 'DREAMCAR-ADAS',
        description: '岚图梦想家车型的智能驾驶系统项目（L2+级别）',
        domain: 'ADAS',
        startDate: '2025-10-01',
        endDate: '2026-06-30',
        status: 'IN_PROGRESS',
        baselines: [
          {
            id: 'bl-sop-2026',
            projectId: 'proj-dreamcar-adas',
            name: 'SOP基线（2026Q2）',
            code: 'BL-SOP-2026Q2',
            targetDate: '2026-06-30',
            status: 'INITIAL_FROZEN',
            maturity: 92,
            completion: 65,
            milestones: standardMilestones,
            gateways: standardGateways,
            productVersions: [
              {
                id: 'pv-noa-1.1-plan',
                productName: '城市NOA',
                version: 'V1.1',
                targetDate: '2026-06-30',
                status: 'IN_PROGRESS',
                completion: 65,
                estimatedHours: 15000,
                sprints: ['sprint-1', 'sprint-2', 'sprint-3'],
              },
            ],
            moduleVersions: [
              {
                id: 'mv-perception-plan',
                moduleName: '感知模块',
                version: 'V1.1',
                teamName: '感知团队',
                status: 'IN_PROGRESS',
                sprints: [
                  {
                    id: 'sprint-perception-1',
                    name: 'Sprint 1 (2026-01)',
                    code: 'SP-PERCEPTION-202601',
                    teamName: '感知团队',
                    startDate: '2026-01-06',
                    endDate: '2026-01-31',
                    status: 'DONE',
                    capacity: 100,
                    committed: 95,
                    completed: 95,
                    workItems: [],
                  },
                  {
                    id: 'sprint-perception-2',
                    name: 'Sprint 2 (2026-02)',
                    code: 'SP-PERCEPTION-202602',
                    teamName: '感知团队',
                    startDate: '2026-02-01',
                    endDate: '2026-02-28',
                    status: 'IN_PROGRESS',
                    capacity: 100,
                    committed: 98,
                    completed: 70,
                    workItems: [],
                  },
                ],
              },
            ],
          },
        ],
        pis: [
          { id: 'pi-2026-q1', name: 'PI-2026-Q1', startDate: '2026-01-01', endDate: '2026-03-31' },
          { id: 'pi-2026-q2', name: 'PI-2026-Q2', startDate: '2026-04-01', endDate: '2026-06-30' },
        ],
      },
      // 项目2：岚图追光 ADAS项目（新增）
      {
        id: 'proj-freelight-adas',
        name: '岚图追光 ADAS项目',
        code: 'FREELIGHT-ADAS',
        description: '岚图追光车型的智能驾驶系统项目（L2+级别）',
        domain: 'ADAS',
        startDate: '2026-01-01',
        endDate: '2026-12-31',
        status: 'IN_PROGRESS',
        baselines: [
          {
            id: 'bl-freelight-sop',
            projectId: 'proj-freelight-adas',
            name: 'SOP基线（2026Q4）',
            code: 'BL-FREELIGHT-2026Q4',
            targetDate: '2026-12-31',
            status: 'PLANNING',
            maturity: 75,
            completion: 30,
            milestones: [
              { id: 'ms-fl-vff', code: 'VFF', name: 'VFF-整车功能冻结', targetDate: '2026-06-15' },
              { id: 'ms-fl-vif', code: 'VIF', name: 'VIF-车辆集成冻结', targetDate: '2026-08-31' },
              { id: 'ms-fl-sop', code: 'SOP', name: 'SOP-量产启动', targetDate: '2026-12-31' },
            ],
            gateways: [
              { id: 'gw-fl-g1', name: 'G1-项目启动', date: '2026-01-01' },
              { id: 'gw-fl-g2', name: 'G2-需求评审', date: '2026-04-30' },
              { id: 'gw-fl-g5', name: 'G5-SOP就绪', date: '2026-12-15' },
            ],
            productVersions: [],
            moduleVersions: [],
          },
        ],
        pis: [],
      },
      // 项目3：知行V9 ADAS项目（新增）
      {
        id: 'proj-v9-adas',
        name: '知行V9 ADAS项目',
        code: 'V9-ADAS',
        description: '知行V9车型的智能驾驶系统项目（L2级别）',
        domain: 'ADAS',
        startDate: '2026-03-01',
        endDate: '2027-03-31',
        status: 'PLANNING',
        baselines: [
          {
            id: 'bl-v9-sop',
            projectId: 'proj-v9-adas',
            name: 'SOP基线（2027Q1）',
            code: 'BL-V9-2027Q1',
            targetDate: '2027-03-31',
            status: 'PLANNING',
            maturity: 60,
            completion: 10,
            milestones: [
              { id: 'ms-v9-vff', code: 'VFF', name: 'VFF-整车功能冻结', targetDate: '2026-09-30' },
              { id: 'ms-v9-sop', code: 'SOP', name: 'SOP-量产启动', targetDate: '2027-03-31' },
            ],
            gateways: [
              { id: 'gw-v9-g1', name: 'G1-项目启动', date: '2026-03-01' },
            ],
            productVersions: [],
            moduleVersions: [],
          },
        ],
        pis: [],
      },
    ]
  }

  /**
   * 生成需求树数据（保持V3.0结构）
   */
  generateRequirementTree(): Epic[] {
    // 引用MockDataServiceV3的完整需求树数据
    const MockDataServiceV3 = require('./MockDataServiceV3').default
    return MockDataServiceV3.generateRequirementTree()
  }
}

export default new MockDataServiceV3_1()
export { MockDataServiceV3_1, type FeatureVersion, type ModuleVersion }
